CREATE TYPE "level" AS ENUM (
  'principiantes',
  'intermedios',
  'avanzados'
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "birthday" date DEFAULT '2000/01/01'
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "level" level NOT NULL,
  "teacher" varchar NOT NULL,
  "user_id" int
);

CREATE TABLE "Courses_Video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_video" varchar NOT NULL,
  "video_url" varchar NOT NULL,
  "courses_id" int,
  "category_id" int
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "Courses" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Courses_Video" ADD FOREIGN KEY ("courses_id") REFERENCES "Courses" ("id");

ALTER TABLE "Courses_Video" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("id");

insert into "Users" (first_name, last_name, email, "password", birthday) values ('Antonio', 'Ortiz', 'arkanamos@gmail.com', 1234, '1985-08-16');
insert into "Users" (first_name, last_name, email, "password", birthday) values ('Vanessa', 'Delgado', 'mathers@gmail.com', 1122, '1984-08-04');

insert into "Courses" (title, description, "level", teacher, user_id) values ('Reactjs', 'lorem ipsum', 'principiantes', 'Junior', 1);
insert into "Courses" (title, description, "level", teacher, user_id) values ('JavaScript', 'lorem ipsum2', 'intermedios', 'Josue', 2);

insert into "Courses_Video" (title_video, video_url, courses_id) values ('React para principiantes', 'videourl', 1);
insert into "Courses_Video" (title_video, video_url, courses_id) values ('Java Scriptpara intermedios', 'videour2', 2);
insert into "Courses_Video" (title_video, video_url, courses_id, category_id) values ('reactjs principiantes', 'link', 1, 1);
insert into "Courses_Video" (title_video, video_url, courses_id, category_id) values ('reactjs principiantes', 'link', 1, 3);

insert into "Categories" (name) values ('Desarrollo web');
insert into "Categories" (name) values ('Desarrollo back end');
 DELETE FROM "Categories"  WHERE id = 1;
 UPDATE  "Categories"  set  id = 1 WHERE id = 2;
