CREATE TYPE "level" AS ENUM (
  'principiantes',
  'intermedios',
  'avanzados'
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "birthday" date DEFAULT '2000/01/01'
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "level" level NOT NULL,
  "teacher" varchar NOT NULL,
  "user_id" int
);

CREATE TABLE "Courses_Video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_video" varchar NOT NULL,
  "video_url" varchar NOT NULL,
  "courses_id" int,
  "category_id" int
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "Courses" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Courses_Video" ADD FOREIGN KEY ("courses_id") REFERENCES "Courses" ("id");

ALTER TABLE "Courses_Video" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("id");
